spring:
  application:
    name: repository
  profiles:
    active: "dev"
server:
  port: ${SERVER_PORT:9011}

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/smartheating_db?verifyServerCertificate=false&useSSL=true&createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/smartheating_db?verifyServerCertificate=false&useSSL=true&createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistration:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    
---
spring:
  profiles: aws
  datasource:
    url: jdbc:mysql://${MYSQL_PRIVATE_IP}:3306/smartheating_db?verifyServerCertificate=false&useSSL=true&createDatabaseIfNotExist=true&serverTimezone=Europe/Berlin
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://${SERVICE_REGISTRATION_PRIVATE_IP}:9000/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    homePageUrl: http://${PRIVATE_IP}:9011/